---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    container_name: lxdhub
  roles:
    - role: check_snap
    - role: lxdhub_container
- hosts: containers
  connection: lxd
  gather_facts: True
  vars:
    container_name: lxdhub
  roles:
    - role: lxd_setup
    - role: node_setup
    - role: postgres_setup
    - role: lxdhub_config
    - role: build
    - role: lxdhub_service
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    container_name: lxdhub
  roles:
    - role: lxdhub_publish
