---
- name: install nginx
  apt:
    name: nginx
    state: present
  become: yes

- name: extract container ip
  shell: lxc ls "{{ container_name }}" -c n4 --format csv | grep -v lxdbr | cut -d, -f2 | cut -d ' ' -f1 | tr -d '"'
  register: lxdhub_container_ip

- name: configure template
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
  notify: restart nginx
  become: yes
