---
- name: install nginx
  apt:
    name: nginx
    state: present
  become: yes

- name: configure template
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
  notify: restart nginx
  become: yes
